typedef enum gstates
{
	NEW_GAME_AI,
	SELECT_NODE_PLAYER,
	SELECT_NODE_AI,
	WEIGH_OPTIONS_AI,
	TURN_PLAYER,
	TURN_AI,
	SEND_UNITS_PLAYER,
	SEND_UNITS_AI,
	END_TURN_AI,
	END_TURN_PLAYER,
	PLAYER_WIN,
	AI_WIN
}GAME_STATES_AI;

typedef enum gstates2{
	NEW_GAME_LOCAL,
	SELECT_NODE_PLAYER1,
	SELECT_NODE_PLAYER2,
	TURN_PLAYER1,
	TURN_PLAYER2,
	SEND_UNITS_PLAYER1,
	SEND_UNITS_PLAYER2,
	END_TURN_PLAYER1,
	END_TURN_PLAYER2,
	PLAYER1_WIN,
	PLAYER2_WIN
}GAME_STATES_LOCAL;